get http://localhost:3000/

###Get dos usuarios
get http://localhost:3000/usuarios

### get com id filtro
get http://localhost:3000/usuario/1

### criar um novo usuario
post http://localhost:3000/cadastro
Content-Type: application/json

{
"nome": "Pedro",
"email": "pedro@gmail.com"
}

### PUT
put http://localhost:3000/editar/1
Content-Type: application/json

{
"nome":"João Vitor"
}

### deletar
delete http://localhost:3000/deletar/1
